cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAU57TVT4LDGJYRPPH
      secret-key: 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
#      useDefaultAwsCredentialsChain: true #Will use credentials in /.aws
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/339276570390/sqs-queue


server:
  port: 8083