spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration

cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAU57TVT4LDGJYRPPH
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/339276570390/sqs-queue


server:
  port: 8083